services:
  - type: web
    name: TiendaClaudia
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: PHP_VERSION
        value: 8.1
